export const WINDOW_SUSPENSE_SYNC_CALLBACKS_KEY = "__SUSPENSE_SYNC_CALLBACKS__";
export const WINDOW_SUSPENSE_SYNC_DATA_KEY = "__SUSPENSE_SYNC_DATA__";
export const WINDOW_SUSPENSE_SYNC_FUNC_KEY = "__SUSPENSE_SYNC_FUNC__";
